ki_icons = \
    [(x.decode('hex').decode("utf-8"), "<" + y + ">") for x, y in [
    ("EFB08F", "RSAP"),
    ("EFB08E", "HFP"),
    ("EFB08D", "DATA"),
    ("EFB080", "BATTERY_4"),
    ("EFB081", "BATTERY_3"),
    ("EFB082", "BATTERY_2"),
    ("EFB083", "BATTERY_1"),
    ("EFB084", "BATTERY_0"),
    ("EFAC8F", "PLAYER"),
    ("EFAC8E", "3G"),
    ("EF9FBD", "CALL_FORWARD"),
    ("EF9FBB", "SMS"),
    ("EFA082", "GPRS_DATA"),
    ("EFA081", "GPRS_ACTIVE"),
    ("EFA080", "HEADSET"),
    ("EF9FBF", "BT_VISIBLE"),
    ("EF9FBE", "BT_ACTIVE"),
    ("EFA08C", "RSS_P_4"),
    ("EFA08B", "RSS_P_3"),
    ("EFA08A", "RSS_P_2"),
    ("EFA089", "RSS_P_1"),
    ("EFA088", "RSS_P_0"),
    ("EFA087", "RSS_A_4"),
    ("EFA086", "RSS_A_3"),
    ("EFA085", "RSS_A_2"),
    ("EFA084", "RSS_A_1"),
    ("EFA083", "RSS_A_0"),
    ("EF9FB8", "LETTER_CLOSED"),
    ("EF9FB7", "LETTER_OPEN"),
    ("EF9FB9", "DEFAULT"),
    ("EF9FB6", "MOBILE"),
    ("EF9FB5", "PRIVATE"),
    ("EF9FB4", "BUSINESS"),
    ("EFA28B", "ROAMING2"),
    ("EFB08B", "ROAMING1"),
    ]]